ambassador:
  replicaCount: 2
  service:
    type: NodePort
    ports:
      - name: https
        port: 443
        targetPort: 8443
        protocol: TCP
        nodePort: 30443
  adminService:
    type: NodePort
    nodePort: 38877
  resources:
    limits:
     cpu: 100m
     memory: 128Mi
    requests:
     cpu: 100m
     memory: 128Mi

  enableAES: true

  redis:
    create: false

  authService:
    create: false

  rateLimit:
    create: false
